/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.19
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  LoginUserParams,
  User
} from '.././model'



/**
 * This can only be done by the logged in user.
 * @summary Create user
 */
export type createUserResponse = {
  data: User;
  status: number;
}

export const getCreateUserUrl = () => {


  return `https://petstore3.swagger.io/api/v3/user`
}

export const createUser = async (user: User, options?: RequestInit): Promise<createUserResponse> => {
  
  const res = await fetch(getCreateUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      user,)
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}




export const getCreateUserMutationOptions = <TError = Promise<User>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: User}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: User}, TContext> => {
const {mutation: mutationOptions, fetch: fetchOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {data: User}> = (props) => {
          const {data} = props ?? {};

          return  createUser(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = User
    export type CreateUserMutationError = Promise<User>

    /**
 * @summary Create user
 */
export const useCreateUser = <TError = Promise<User>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: User}, TContext>, fetch?: RequestInit}
): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: User},
        TContext
      > => {

      const mutationOptions = getCreateUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Creates list of users with given input array
 * @summary Creates list of users with given input array
 */
export type createUsersWithListInputResponse = {
  data: User;
  status: number;
}

export const getCreateUsersWithListInputUrl = () => {


  return `https://petstore3.swagger.io/api/v3/user/createWithList`
}

export const createUsersWithListInput = async (user: User[], options?: RequestInit): Promise<createUsersWithListInputResponse> => {
  
  const res = await fetch(getCreateUsersWithListInputUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      user,)
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}




export const getCreateUsersWithListInputMutationOptions = <TError = Promise<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUsersWithListInput>>, TError,{data: User[]}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createUsersWithListInput>>, TError,{data: User[]}, TContext> => {
const {mutation: mutationOptions, fetch: fetchOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUsersWithListInput>>, {data: User[]}> = (props) => {
          const {data} = props ?? {};

          return  createUsersWithListInput(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUsersWithListInputMutationResult = NonNullable<Awaited<ReturnType<typeof createUsersWithListInput>>>
    export type CreateUsersWithListInputMutationBody = User[]
    export type CreateUsersWithListInputMutationError = Promise<void>

    /**
 * @summary Creates list of users with given input array
 */
export const useCreateUsersWithListInput = <TError = Promise<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUsersWithListInput>>, TError,{data: User[]}, TContext>, fetch?: RequestInit}
): UseMutationResult<
        Awaited<ReturnType<typeof createUsersWithListInput>>,
        TError,
        {data: User[]},
        TContext
      > => {

      const mutationOptions = getCreateUsersWithListInputMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Logs user into the system
 */
export type loginUserResponse = {
  data: string;
  status: number;
}

export const getLoginUserUrl = (params?: LoginUserParams,) => {

  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value === null) {
      normalizedParams.append(key, 'null');
    } else if (value !== undefined) {
      normalizedParams.append(key, value.toString());
    }
  });

  return normalizedParams.size ? `https://petstore3.swagger.io/api/v3/user/login?${normalizedParams.toString()}` : `https://petstore3.swagger.io/api/v3/user/login`
}

export const loginUser = async (params?: LoginUserParams, options?: RequestInit): Promise<loginUserResponse> => {
  
  const res = await fetch(getLoginUserUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}



export const getLoginUserQueryKey = (params?: LoginUserParams,) => {
    return [`https://petstore3.swagger.io/api/v3/user/login`, ...(params ? [params]: [])] as const;
    }

    
export const getLoginUserInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof loginUser>>, LoginUserParams['nextId']>, TError = Promise<void>>(params?: LoginUserParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData, Awaited<ReturnType<typeof loginUser>>, QueryKey, LoginUserParams['nextId']>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginUserQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loginUser>>, QueryKey, LoginUserParams['nextId']> = ({ signal, pageParam }) => loginUser({...params, nextId: pageParam || params?.['nextId']}, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 60000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData, Awaited<ReturnType<typeof loginUser>>, QueryKey, LoginUserParams['nextId']> & { queryKey: QueryKey }
}

export type LoginUserInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
export type LoginUserInfiniteQueryError = Promise<void>


export function useLoginUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof loginUser>>, LoginUserParams['nextId']>, TError = Promise<void>>(
 params: undefined |  LoginUserParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData, Awaited<ReturnType<typeof loginUser>>, QueryKey, LoginUserParams['nextId']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginUser>>,
          TError,
          TData, QueryKey
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useLoginUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof loginUser>>, LoginUserParams['nextId']>, TError = Promise<void>>(
 params?: LoginUserParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData, Awaited<ReturnType<typeof loginUser>>, QueryKey, LoginUserParams['nextId']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginUser>>,
          TError,
          TData, QueryKey
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useLoginUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof loginUser>>, LoginUserParams['nextId']>, TError = Promise<void>>(
 params?: LoginUserParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData, Awaited<ReturnType<typeof loginUser>>, QueryKey, LoginUserParams['nextId']>>, fetch?: RequestInit}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Logs user into the system
 */

export function useLoginUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof loginUser>>, LoginUserParams['nextId']>, TError = Promise<void>>(
 params?: LoginUserParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData, Awaited<ReturnType<typeof loginUser>>, QueryKey, LoginUserParams['nextId']>>, fetch?: RequestInit}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getLoginUserInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getLoginUserQueryOptions = <TData = Awaited<ReturnType<typeof loginUser>>, TError = Promise<void>>(params?: LoginUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginUserQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loginUser>>> = ({ signal }) => loginUser(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 60000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData> & { queryKey: QueryKey }
}

export type LoginUserQueryResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
export type LoginUserQueryError = Promise<void>


export function useLoginUser<TData = Awaited<ReturnType<typeof loginUser>>, TError = Promise<void>>(
 params: undefined |  LoginUserParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginUser>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useLoginUser<TData = Awaited<ReturnType<typeof loginUser>>, TError = Promise<void>>(
 params?: LoginUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginUser>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useLoginUser<TData = Awaited<ReturnType<typeof loginUser>>, TError = Promise<void>>(
 params?: LoginUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Logs user into the system
 */

export function useLoginUser<TData = Awaited<ReturnType<typeof loginUser>>, TError = Promise<void>>(
 params?: LoginUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getLoginUserQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Logs out current logged in user session
 */
export type logoutUserResponse = {
  data: void;
  status: number;
}

export const getLogoutUserUrl = () => {


  return `https://petstore3.swagger.io/api/v3/user/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {
  
  const res = await fetch(getLogoutUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}



export const getLogoutUserQueryKey = () => {
    return [`https://petstore3.swagger.io/api/v3/user/logout`] as const;
    }

    
export const getLogoutUserInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof logoutUser>>>, TError = Promise<void>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogoutUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof logoutUser>>> = ({ signal }) => logoutUser({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 60000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData> & { queryKey: QueryKey }
}

export type LogoutUserInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>
export type LogoutUserInfiniteQueryError = Promise<void>


export function useLogoutUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof logoutUser>>>, TError = Promise<void>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutUser>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useLogoutUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof logoutUser>>>, TError = Promise<void>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutUser>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useLogoutUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof logoutUser>>>, TError = Promise<void>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>>, fetch?: RequestInit}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Logs out current logged in user session
 */

export function useLogoutUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof logoutUser>>>, TError = Promise<void>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>>, fetch?: RequestInit}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getLogoutUserInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getLogoutUserQueryOptions = <TData = Awaited<ReturnType<typeof logoutUser>>, TError = Promise<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogoutUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof logoutUser>>> = ({ signal }) => logoutUser({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 60000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData> & { queryKey: QueryKey }
}

export type LogoutUserQueryResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>
export type LogoutUserQueryError = Promise<void>


export function useLogoutUser<TData = Awaited<ReturnType<typeof logoutUser>>, TError = Promise<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutUser>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useLogoutUser<TData = Awaited<ReturnType<typeof logoutUser>>, TError = Promise<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutUser>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useLogoutUser<TData = Awaited<ReturnType<typeof logoutUser>>, TError = Promise<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Logs out current logged in user session
 */

export function useLogoutUser<TData = Awaited<ReturnType<typeof logoutUser>>, TError = Promise<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getLogoutUserQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get user by user name
 */
export type getUserByNameResponse = {
  data: User;
  status: number;
}

export const getGetUserByNameUrl = (username: string,) => {


  return `https://petstore3.swagger.io/api/v3/user/${username}`
}

export const getUserByName = async (username: string, options?: RequestInit): Promise<getUserByNameResponse> => {
  
  const res = await fetch(getGetUserByNameUrl(username),
  {      
    ...options,
    method: 'GET'
    
    
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}



export const getGetUserByNameQueryKey = (username: string,) => {
    return [`https://petstore3.swagger.io/api/v3/user/${username}`] as const;
    }

    
export const getGetUserByNameInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getUserByName>>>, TError = Promise<void>>(username: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserByNameQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserByName>>> = ({ signal }) => getUserByName(username, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(username),  staleTime: 60000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserByNameInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getUserByName>>>
export type GetUserByNameInfiniteQueryError = Promise<void>


export function useGetUserByNameInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserByName>>>, TError = Promise<void>>(
 username: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByName>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserByNameInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserByName>>>, TError = Promise<void>>(
 username: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByName>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserByNameInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserByName>>>, TError = Promise<void>>(
 username: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>>, fetch?: RequestInit}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get user by user name
 */

export function useGetUserByNameInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserByName>>>, TError = Promise<void>>(
 username: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>>, fetch?: RequestInit}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserByNameInfiniteQueryOptions(username,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetUserByNameQueryOptions = <TData = Awaited<ReturnType<typeof getUserByName>>, TError = Promise<void>>(username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserByNameQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserByName>>> = ({ signal }) => getUserByName(username, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(username),  staleTime: 60000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getUserByName>>>
export type GetUserByNameQueryError = Promise<void>


export function useGetUserByName<TData = Awaited<ReturnType<typeof getUserByName>>, TError = Promise<void>>(
 username: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByName>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserByName<TData = Awaited<ReturnType<typeof getUserByName>>, TError = Promise<void>>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByName>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserByName<TData = Awaited<ReturnType<typeof getUserByName>>, TError = Promise<void>>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get user by user name
 */

export function useGetUserByName<TData = Awaited<ReturnType<typeof getUserByName>>, TError = Promise<void>>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserByNameQueryOptions(username,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * This can only be done by the logged in user.
 * @summary Update user
 */
export type updateUserResponse = {
  data: void;
  status: number;
}

export const getUpdateUserUrl = (username: string,) => {


  return `https://petstore3.swagger.io/api/v3/user/${username}`
}

export const updateUser = async (username: string,
    user: User, options?: RequestInit): Promise<updateUserResponse> => {
  
  const res = await fetch(getUpdateUserUrl(username),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      user,)
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}




export const getUpdateUserMutationOptions = <TError = Promise<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{username: string;data: User}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{username: string;data: User}, TContext> => {
const {mutation: mutationOptions, fetch: fetchOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {username: string;data: User}> = (props) => {
          const {username,data} = props ?? {};

          return  updateUser(username,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = User
    export type UpdateUserMutationError = Promise<void>

    /**
 * @summary Update user
 */
export const useUpdateUser = <TError = Promise<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{username: string;data: User}, TContext>, fetch?: RequestInit}
): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {username: string;data: User},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * This can only be done by the logged in user.
 * @summary Delete user
 */
export type deleteUserResponse = {
  data: unknown;
  status: number;
}

export const getDeleteUserUrl = (username: string,) => {


  return `https://petstore3.swagger.io/api/v3/user/${username}`
}

export const deleteUser = async (username: string, options?: RequestInit): Promise<deleteUserResponse> => {
  
  const res = await fetch(getDeleteUserUrl(username),
  {      
    ...options,
    method: 'DELETE'
    
    
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}




export const getDeleteUserMutationOptions = <TError = Promise<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{username: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{username: string}, TContext> => {
const {mutation: mutationOptions, fetch: fetchOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {username: string}> = (props) => {
          const {username} = props ?? {};

          return  deleteUser(username,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = Promise<void>

    /**
 * @summary Delete user
 */
export const useDeleteUser = <TError = Promise<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{username: string}, TContext>, fetch?: RequestInit}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {username: string},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    