import type { Metadata } from "next";
import { wavveFont } from "@/app/fonts";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(wavveFont.className)}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
