import React from "react";

import type { Metadata } from "next";
import "./globals.css";

import { lineFont } from "@/app/fonts";
import AuthEventListener from "@/components/auth/AuthEventListener";
import { cn } from "@/lib/utils";
import QueryProvider from "@/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(lineFont.variable)}>
        <QueryProvider>
          <main className="flex min-h-screen justify-center">
            <section className="flex flex-col min-h-screen h-full max-w-screen-md w-full bg-background">
              {children}
            </section>
          </main>
          <AuthEventListener />
        </QueryProvider>
      </body>
    </html>
  );
}
