import type { Metadata } from "next";
import {
  cafe24MoyamoyaFont,
  cafe24SupermagicFont,
  cafe24OhsquareFont,
  cafe24OhsquareAirFont,
} from "@/app/fonts";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          cafe24OhsquareAirFont.variable,
          cafe24OhsquareFont.variable,
          cafe24SupermagicFont.variable,
          cafe24MoyamoyaFont.variable,
        )}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
