name: Slack Notifications

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: [closed]

jobs:
  notify-slack:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Setup GitHub CLI
      - name: Setup GitHub CLI
        run: |
          if ! gh --version; then
            sudo apt-get install gh
          fi

      # Authenticate GitHub CLI using GITHUB_TOKEN
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token


      # Notify Slack
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          const pull_requst = context.payload.pull_request; #pull_request 객체 가져오기
          
          if (pull_requst === undefined) {  # pull_requst가 없는 경우
            console.log("The corresponding PR cannot be verified.")
            return;
          }
          
          const pr_body = pull_requst.body;
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${{pr_body}}"}' $SLACK_WEBHOOK_URL